### ISSUE TITLE
Audio skip

### ISSUE THREAD

**Issue by dkogan** [kristopolous/DRR#146] opened 2015-09-30 04:34 UTC
Don't know if you still care about this. If you do, then play

http://indycast.net/kpcc/live/21:00:00

There's a skip (stream jumps to an entirely different show) at 13:55

**Comment by kristopolous** [comment] 2015-09-30 06:04
you caught up to it I'm guessing. if you go right now http://indycast.net/kpcc/live/21:13:50 you'll see that it's fine.

**Comment by dkogan** [comment] 2015-09-30 06:14
Chris McKenzie notifications@github.com writes:

> you caught up to it I'm guessing. if you go right now
> http://indycast.net/kpcc/live/21:13:50 you'll see that it's fine.

I don't understand. I can read from that link, but whatever it sounds
like doesn't change the fact that the other link jumps. Or are you
saying the source material has a jump?

**Comment by kristopolous** [comment] 2015-09-30 06:17
mpv --start 13:50 http://indycast.net/kpcc/live/21:00:00

It is 100% continuous.

**Comment by dkogan** [comment] 2015-09-30 06:22
Chris McKenzie notifications@github.com writes:

> mpv --start 13:50 http://indycast.net/kpcc/live/21:00:00
> 
> It is 100% continuous.

I just tried again. Yes, it works now. I'm however 100% sure that I
didn't catch up to it. I turned on live kpcc at about 21:15, then
decided to listen to that show from the start, and tuned into this
indycast stream that was delayed by about 15 min. I didn't touch the
player of that stream, i.e. I didn't seek forward, so it should have
remained 15 minutes in the past the whole time. And I'm 100% sure that
this is the correct link and that I observed the issue at that time
point. It jumped to a different show entirely, not even a different part
of the same show.

**Comment by kristopolous** [comment] 2015-09-30 06:27
20150930_0413_07 - INFO - ua - Opera/9.80 (X11; Linux x86_64) Presto/2.12.388 Version/12.16
20150930_0413_08 - DEBUG - -- opening streams/kpcc-201509292055.mp3 7593984 2406191 2406191
20150930_0413_08 - INFO - 50.1.153.216 - - [30/Sep/2015 04:13:08] "GET /live/21%3A00%3A00 HTTP/1.1" 200 -
20150930_0413_15 - INFO - ua - Opera/9.80 (X11; Linux x86_64) Presto/2.12.388 Version/12.16
20150930_0413_16 - DEBUG - -- opening streams/kpcc-201509292055.mp3 7593984 2404728 2404728
20150930_0413_16 - INFO - 50.1.153.216 - - [30/Sep/2015 04:13:16] "GET /live/21%3A00%3A00 HTTP/1.1" 200 -
20150930_0413_26 - INFO - ua - Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)
20150930_0413_26 - DEBUG - -- opening streams/kpcc-201509292055.mp3 7593984 2402220 2402220
20150930_0413_26 - INFO - 50.1.153.216 - - [30/Sep/2015 04:13:26] "GET /live/21%3A00%3A00 HTTP/1.1" 200 -
20150930_0413_26 - INFO - ua - Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)
20150930_0413_26 - INFO - 50.1.153.216 - - [30/Sep/2015 04:13:26] "HEAD /live/21%3A00%3A00 HTTP/1.1" 200 -
20150930_0413_27 - INFO - ua - mpv 0.7.2
20150930_0413_27 - DEBUG - -- opening streams/kpcc-201509292055.mp3 7593984 2401802 2401802
20150930_0413_27 - INFO - 50.1.153.216 - - [30/Sep/2015 04:13:27] "GET /live/21%3A00%3A00 HTTP/1.1" 200 -
20150930_0413_31 - DEBUG - -- closing streams/kpcc-201509292055.mp3 7593984 7593900 24845 5
20150930_0413_32 - DEBUG - -- opening streams/kpcc-201509292110.mp3 1830912 352757 352757
20150930_0413_34 - DEBUG - -- closing streams/kpcc-201509292110.mp3 1830912 1847170 7151 1
20150930_0413_34 - WARNING - Cannot find indices between streams/kpcc-201509292110.mp3 and streams/kpcc-201509292055.mp3
20150930_0413_34 - DEBUG - -- opening streams/kpcc-201509292055.mp3 7593984 418 418

confirmed! you are not crazy.

**Comment by dkogan** [comment] 2015-09-30 06:28
Chris McKenzie notifications@github.com writes:

> 20150930_0413_07 - INFO - ua - Opera/9.80 (X11; Linux x86_64) Presto/2.12.388 Version/12.16
> 20150930_0413_08 - DEBUG - -- opening streams/kpcc-201509292055.mp3 7593984 2406191 2406191
> 20150930_0413_08 - INFO - 50.1.153.216 - - [30/Sep/2015 04:13:08] "GET /live/21%3A00%3A00 HTTP/1.1" 200 -
> 20150930_0413_15 - INFO - ua - Opera/9.80 (X11; Linux x86_64) Presto/2.12.388 Version/12.16
> 20150930_0413_16 - DEBUG - -- opening streams/kpcc-201509292055.mp3 7593984 2404728 2404728
> 20150930_0413_16 - INFO - 50.1.153.216 - - [30/Sep/2015 04:13:16] "GET /live/21%3A00%3A00 HTTP/1.1" 200 -
> 20150930_0413_26 - INFO - ua - Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)
> 20150930_0413_26 - DEBUG - -- opening streams/kpcc-201509292055.mp3 7593984 2402220 2402220
> 20150930_0413_26 - INFO - 50.1.153.216 - - [30/Sep/2015 04:13:26] "GET /live/21%3A00%3A00 HTTP/1.1" 200 -
> 20150930_0413_26 - INFO - ua - Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)
> 20150930_0413_26 - INFO - 50.1.153.216 - - [30/Sep/2015 04:13:26] "HEAD /live/21%3A00%3A00 HTTP/1.1" 200 -
> 20150930_0413_27 - INFO - ua - mpv 0.7.2
> 20150930_0413_27 - DEBUG - -- opening streams/kpcc-201509292055.mp3 7593984 2401802 2401802
> 20150930_0413_27 - INFO - 50.1.153.216 - - [30/Sep/2015 04:13:27] "GET /live/21%3A00%3A00 HTTP/1.1" 200 -
> 20150930_0413_31 - DEBUG - -- closing streams/kpcc-201509292055.mp3 7593984 7593900 24845 5
> 20150930_0413_32 - DEBUG - -- opening streams/kpcc-201509292110.mp3 1830912 352757 352757
> 20150930_0413_34 - DEBUG - -- closing streams/kpcc-201509292110.mp3 1830912 1847170 7151 1
> 20150930_0413_34 - WARNING - Cannot find indices between streams/kpcc-201509292110.mp3 and streams/kpcc-201509292055.mp3
> 20150930_0413_34 - DEBUG - -- opening streams/kpcc-201509292055.mp3 7593984 418 418
> 
> confirmed! you are not crazy.

Nice. That may as well be my personal user agent string.

**Comment by kristopolous** [comment] 2015-09-30 06:31
it's definitely a calling card.  Anyway, this is one of those heisenbugs since it has no problem whatsoever finding a link between the mp3s now :-(

**Comment by kristopolous** [comment] 2015-09-30 08:17
oh look the problem is obvious ... it goes back in time.

> Cannot find indices between streams/kpcc-201509292110.mp3 and streams/kpcc-201509292055.mp3

Those are timestamps ... it's trying to link 9:10 before 8;55  ... not going to work.

**Comment by kristopolous** [comment] 2015-09-30 08:22
so what happens is around https://github.com/kristopolous/DRR/blob/master/server/lib/audio.py#L778 
and then https://github.com/kristopolous/DRR/blob/master/server/lib/cloud.py#L360

The problem here is that it determined that the "closest" audio is the one it was just using.  It should really bias that to +1 (see https://github.com/kristopolous/DRR/blob/master/server/lib/cloud.py#L273).  Probably changing the get_next to have a positive bias would do it

**Comment by kristopolous** [comment] 2015-09-30 08:25
It was +1 but then I changed it to none to try to fix this problem before in #98. Ug ... gotta find out what's wrong for real I guess

**Comment by kristopolous** [comment] 2016-04-11 23:20
i'm guessing this is fine.

**Closed as completed by kristopolous** 2016-04-11 23:20 UTC
